/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kao_face_TinyCnnJni */

#ifndef _Included_com_kao_face_TinyCnnJni
#define _Included_com_kao_face_TinyCnnJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kao_face_TinyCnnJni
 * Method:    test_jni
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_kao_face_TinyCnnJni_test_1jni
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_kao_face_TinyCnnJni
 * Method:    test_tinycnn_jni
 * Signature: ([BII[BI[BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kao_face_TinyCnnJni_test_1tinycnn_1jni
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_kao_face_TinyCnnJni
 * Method:    init_net_jni
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_kao_face_TinyCnnJni_init_1net_1jni
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_kao_face_TinyCnnJni
 * Method:    train_net_jni
 * Signature: ([BIII[BII)V
 */
JNIEXPORT void JNICALL Java_com_kao_face_TinyCnnJni_train_1net_1jni
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_kao_face_TinyCnnJni
 * Method:    test_net_jni
 * Signature: ([BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kao_face_TinyCnnJni_test_1net_1jni
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
